import { Flower } from './components/HelloWorld.vue';

export interface Game {
  Name: string;
  Board: Array<Array<Flower>>;
}

export const A: Game = {
  Name: 'A',
  Board: [
    [
      { color: 'purple', selected: false },
      { color: 'purple', selected: false },
      { color: 'yellow', selected: false },
      { color: 'yellow', selected: false },
      { color: 'yellow', selected: false },
      { color: 'purple', selected: false },
      { color: 'slate', selected: false },
      { color: 'yellow', selected: false },
      { color: 'yellow', selected: false },
    ],
    [
      { color: 'purple', selected: false },
      { color: 'orange', selected: false },
      { color: 'yellow', selected: false },
      { color: 'slate', selected: false },
      { color: 'orange', selected: false },
      { color: 'purple', selected: false },
      { color: 'orange', selected: false },
      { color: 'orange', selected: false },
      { color: 'orange', selected: false },
    ],
    [
      { color: 'slate', selected: false },
      { color: 'orange', selected: false },
      { color: 'sky', selected: false },
      { color: 'orange', selected: false },
      { color: 'orange', selected: false },
      { color: 'pink', selected: false },
      { color: 'orange', selected: false },
      { color: 'sky', selected: false },
      { color: 'pink', selected: false },
    ],
    [
      { color: 'sky', selected: false },
      { color: 'sky', selected: false },
      { color: 'sky', selected: false },
      { color: 'orange', selected: false },
      { color: 'pink', selected: false },
      { color: 'pink', selected: false },
      { color: 'orange', selected: false },
      { color: 'sky', selected: false },
      { color: 'slate', selected: false },
    ],
    [
      { color: 'pink', selected: false },
      { color: 'purple', selected: false },
      { color: 'purple', selected: false },
      { color: 'purple', selected: false },
      { color: 'purple', selected: false },
      { color: 'slate', selected: false },
      { color: 'yellow', selected: false },
      { color: 'sky', selected: false },
      { color: 'sky', selected: false },
    ],
    [
      { color: 'pink', selected: false },
      { color: 'pink', selected: false },
      { color: 'pink', selected: false },
      { color: 'sky', selected: false },
      { color: 'sky', selected: false },
      { color: 'sky', selected: false },
      { color: 'yellow', selected: false },
      { color: 'yellow', selected: false },
      { color: 'purple', selected: false },
    ],
    [
      { color: 'purple', selected: false },
      { color: 'yellow', selected: false },
      { color: 'sky', selected: false },
      { color: 'orange', selected: false },
      { color: 'orange', selected: false },
      { color: 'pink', selected: false },
      { color: 'yellow', selected: false },
      { color: 'purple', selected: false },
      { color: 'purple', selected: false },
    ],
    [
      { color: 'sky', selected: false },
      { color: 'yellow', selected: false },
      { color: 'yellow', selected: false },
      { color: 'orange', selected: false },
      { color: 'pink', selected: false },
      { color: 'pink', selected: false },
      { color: 'pink', selected: false },
      { color: 'slate', selected: false },
      { color: 'purple', selected: false },
    ],
  ],
};
export const B: Game = {
  Name: 'B',
  Board: [
    [
      { color: 'purple', selected: false },
      { color: 'slate', selected: false },
      { color: 'pink', selected: false },
      { color: 'pink', selected: false },
      { color: 'pink', selected: false },
      { color: 'pink', selected: false },
      { color: 'yellow', selected: false },
      { color: 'yellow', selected: false },
      { color: 'pink', selected: false },
    ],
    [
      { color: 'purple', selected: false },
      { color: 'purple', selected: false },
      { color: 'yellow', selected: false },
      { color: 'sky', selected: false },
      { color: 'orange', selected: false },
      { color: 'orange', selected: false },
      { color: 'slate', selected: false },
      { color: 'sky', selected: false },
      { color: 'orange', selected: false },
    ],
    [
      { color: 'purple', selected: false },
      { color: 'yellow', selected: false },
      { color: 'yellow', selected: false },
      { color: 'sky', selected: false },
      { color: 'orange', selected: false },
      { color: 'orange', selected: false },
      { color: 'sky', selected: false },
      { color: 'sky', selected: false },
      { color: 'orange', selected: false },
    ],
    [
      { color: 'sky', selected: false },
      { color: 'sky', selected: false },
      { color: 'yellow', selected: false },
      { color: 'slate', selected: false },
      { color: 'purple', selected: false },
      { color: 'purple', selected: false },
      { color: 'purple', selected: false },
      { color: 'purple', selected: false },
      { color: 'orange', selected: false },
    ],
    [
      { color: 'slate', selected: false },
      { color: 'sky', selected: false },
      { color: 'orange', selected: false },
      { color: 'orange', selected: false },
      { color: 'sky', selected: false },
      { color: 'sky', selected: false },
      { color: 'orange', selected: false },
      { color: 'orange', selected: false },
      { color: 'orange', selected: false },
    ],
    [
      { color: 'pink', selected: false },
      { color: 'sky', selected: false },
      { color: 'orange', selected: false },
      { color: 'orange', selected: false },
      { color: 'sky', selected: false },
      { color: 'sky', selected: false },
      { color: 'orange', selected: false },
      { color: 'orange', selected: false },
      { color: 'slate', selected: false },
    ],
    [
      { color: 'pink', selected: false },
      { color: 'yellow', selected: false },
      { color: 'yellow', selected: false },
      { color: 'purple', selected: false },
      { color: 'purple', selected: false },
      { color: 'slate', selected: false },
      { color: 'yellow', selected: false },
      { color: 'orange', selected: false },
      { color: 'orange', selected: false },
    ],
    [
      { color: 'pink', selected: false },
      { color: 'yellow', selected: false },
      { color: 'slate', selected: false },
      { color: 'purple', selected: false },
      { color: 'yellow', selected: false },
      { color: 'yellow', selected: false },
      { color: 'yellow', selected: false },
      { color: 'purple', selected: false },
      { color: 'purple', selected: false },
    ],
  ],
};

export const C: Game = {
  Name: 'C',
  Board: [
    [
      { color: 'orange', selected: false },
      { color: 'slate', selected: false },
      { color: 'yellow', selected: false },
      { color: 'pink', selected: false },
      { color: 'pink', selected: false },
      { color: 'sky', selected: false },
      { color: 'purple', selected: false },
      { color: 'purple', selected: false },
      { color: 'yellow', selected: false },
    ],
    [
      { color: 'orange', selected: false },
      { color: 'yellow', selected: false },
      { color: 'yellow', selected: false },
      { color: 'orange', selected: false },
      { color: 'orange', selected: false },
      { color: 'sky', selected: false },
      { color: 'purple', selected: false },
      { color: 'slate', selected: false },
      { color: 'yellow', selected: false },
    ],
    [
      { color: 'orange', selected: false },
      { color: 'orange', selected: false },
      { color: 'purple', selected: false },
      { color: 'slate', selected: false },
      { color: 'sky', selected: false },
      { color: 'sky', selected: false },
      { color: 'orange', selected: false },
      { color: 'pink', selected: false },
      { color: 'pink', selected: false },
    ],
    [
      { color: 'sky', selected: false },
      { color: 'sky', selected: false },
      { color: 'purple', selected: false },
      { color: 'purple', selected: false },
      { color: 'purple', selected: false },
      { color: 'orange', selected: false },
      { color: 'orange', selected: false },
      { color: 'orange', selected: false },
      { color: 'pink', selected: false },
    ],
    [
      { color: 'pink', selected: false },
      { color: 'pink', selected: false },
      { color: 'yellow', selected: false },
      { color: 'yellow', selected: false },
      { color: 'yellow', selected: false },
      { color: 'slate', selected: false },
      { color: 'sky', selected: false },
      { color: 'sky', selected: false },
      { color: 'pink', selected: false },
    ],
    [
      { color: 'slate', selected: false },
      { color: 'pink', selected: false },
      { color: 'yellow', selected: false },
      { color: 'orange', selected: false },
      { color: 'orange', selected: false },
      { color: 'pink', selected: false },
      { color: 'sky', selected: false },
      { color: 'yellow', selected: false },
      { color: 'yellow', selected: false },
    ],
    [
      { color: 'purple', selected: false },
      { color: 'purple', selected: false },
      { color: 'sky', selected: false },
      { color: 'purple', selected: false },
      { color: 'slate', selected: false },
      { color: 'pink', selected: false },
      { color: 'orange', selected: false },
      { color: 'yellow', selected: false },
      { color: 'yellow', selected: false },
    ],
    [
      { color: 'sky', selected: false },
      { color: 'sky', selected: false },
      { color: 'sky', selected: false },
      { color: 'purple', selected: false },
      { color: 'purple', selected: false },
      { color: 'purple', selected: false },
      { color: 'orange', selected: false },
      { color: 'orange', selected: false },
      { color: 'slate', selected: false },
    ],
  ],
};

export const D: Game = {
  Name: 'D',
  Board: [
    [
      { color: 'purple', selected: false },
      { color: 'slate', selected: false },
      { color: 'orange', selected: false },
      { color: 'orange', selected: false },
      { color: 'orange', selected: false },
      { color: 'orange', selected: false },
      { color: 'purple', selected: false },
      { color: 'purple', selected: false },
      { color: 'orange', selected: false },
    ],
    [
      { color: 'purple', selected: false },
      { color: 'sky', selected: false },
      { color: 'sky', selected: false },
      { color: 'yellow', selected: false },
      { color: 'yellow', selected: false },
      { color: 'sky', selected: false },
      { color: 'yellow', selected: false },
      { color: 'slate', selected: false },
      { color: 'orange', selected: false },
    ],
    [
      { color: 'purple', selected: false },
      { color: 'pink', selected: false },
      { color: 'sky', selected: false },
      { color: 'pink', selected: false },
      { color: 'slate', selected: false },
      { color: 'sky', selected: false },
      { color: 'yellow', selected: false },
      { color: 'yellow', selected: false },
      { color: 'pink', selected: false },
    ],
    [
      { color: 'pink', selected: false },
      { color: 'pink', selected: false },
      { color: 'sky', selected: false },
      { color: 'pink', selected: false },
      { color: 'pink', selected: false },
      { color: 'pink', selected: false },
      { color: 'yellow', selected: false },
      { color: 'pink', selected: false },
      { color: 'pink', selected: false },
    ],
    [
      { color: 'yellow', selected: false },
      { color: 'pink', selected: false },
      { color: 'orange', selected: false },
      { color: 'purple', selected: false },
      { color: 'purple', selected: false },
      { color: 'purple', selected: false },
      { color: 'purple', selected: false },
      { color: 'orange', selected: false },
      { color: 'slate', selected: false },
    ],
    [
      { color: 'yellow', selected: false },
      { color: 'yellow', selected: false },
      { color: 'orange', selected: false },
      { color: 'slate', selected: false },
      { color: 'pink', selected: false },
      { color: 'pink', selected: false },
      { color: 'orange', selected: false },
      { color: 'orange', selected: false },
      { color: 'sky', selected: false },
    ],
    [
      { color: 'slate', selected: false },
      { color: 'purple', selected: false },
      { color: 'orange', selected: false },
      { color: 'sky', selected: false },
      { color: 'yellow', selected: false },
      { color: 'yellow', selected: false },
      { color: 'yellow', selected: false },
      { color: 'orange', selected: false },
      { color: 'sky', selected: false },
    ],
    [
      { color: 'purple', selected: false },
      { color: 'purple', selected: false },
      { color: 'purple', selected: false },
      { color: 'sky', selected: false },
      { color: 'sky', selected: false },
      { color: 'slate', selected: false },
      { color: 'yellow', selected: false },
      { color: 'sky', selected: false },
      { color: 'sky', selected: false },
    ],
  ],
};
export const E: Game = {
  Name: 'E',
  Board: [
    [
      { color: 'orange', selected: false },
      { color: 'orange', selected: false },
      { color: 'orange', selected: false },
      { color: 'sky', selected: false },
      { color: 'sky', selected: false },
      { color: 'purple', selected: false },
      { color: 'slate', selected: false },
      { color: 'yellow', selected: false },
      { color: 'yellow', selected: false },
    ],
    [
      { color: 'purple', selected: false },
      { color: 'purple', selected: false },
      { color: 'pink', selected: false },
      { color: 'slate', selected: false },
      { color: 'sky', selected: false },
      { color: 'purple', selected: false },
      { color: 'purple', selected: false },
      { color: 'yellow', selected: false },
      { color: 'yellow', selected: false },
    ],
    [
      { color: 'purple', selected: false },
      { color: 'purple', selected: false },
      { color: 'pink', selected: false },
      { color: 'orange', selected: false },
      { color: 'sky', selected: false },
      { color: 'purple', selected: false },
      { color: 'orange', selected: false },
      { color: 'orange', selected: false },
      { color: 'orange', selected: false },
    ],
    [
      { color: 'slate', selected: false },
      { color: 'sky', selected: false },
      { color: 'pink', selected: false },
      { color: 'orange', selected: false },
      { color: 'yellow', selected: false },
      { color: 'yellow', selected: false },
      { color: 'pink', selected: false },
      { color: 'pink', selected: false },
      { color: 'orange', selected: false },
    ],
    [
      { color: 'pink', selected: false },
      { color: 'sky', selected: false },
      { color: 'sky', selected: false },
      { color: 'purple', selected: false },
      { color: 'purple', selected: false },
      { color: 'purple', selected: false },
      { color: 'pink', selected: false },
      { color: 'pink', selected: false },
      { color: 'slate', selected: false },
    ],
    [
      { color: 'pink', selected: false },
      { color: 'sky', selected: false },
      { color: 'yellow', selected: false },
      { color: 'pink', selected: false },
      { color: 'slate', selected: false },
      { color: 'sky', selected: false },
      { color: 'yellow', selected: false },
      { color: 'yellow', selected: false },
      { color: 'yellow', selected: false },
    ],
    [
      { color: 'purple', selected: false },
      { color: 'yellow', selected: false },
      { color: 'yellow', selected: false },
      { color: 'pink', selected: false },
      { color: 'sky', selected: false },
      { color: 'sky', selected: false },
      { color: 'orange', selected: false },
      { color: 'slate', selected: false },
      { color: 'sky', selected: false },
    ],
    [
      { color: 'purple', selected: false },
      { color: 'slate', selected: false },
      { color: 'yellow', selected: false },
      { color: 'pink', selected: false },
      { color: 'pink', selected: false },
      { color: 'orange', selected: false },
      { color: 'orange', selected: false },
      { color: 'orange', selected: false },
      { color: 'sky', selected: false },
    ],
  ],
};
export const games: Game[] = [A, B, C, D, E];
